<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun = rerun.strip.gsub /\s/, ' '
rerun_opts = rerun.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
common = "--publish-quiet --strict --tags 'not @wip'"
%>
default: <%= common %> --format summary features
loud: <%= common %> LOUD=true --fail-fast --format pretty features
rerun: <%= common %> <%= rerun_opts %> --format rerun --out rerun.txt'
steps: <%= common %> --dry-run --format stepdefs
wip: --publish-quiet --strict --tags '@wip'
